version: '3.7'
services:
  influxdb:
    image: influxdb:2.7.6
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=[InfluxDB Username]
      - DOCKER_INFLUXDB_INIT_PASSWORD=[InfluxDB Password]
      - DOCKER_INFLUXDB_INIT_ORG=ssafy
      - DOCKER_INFLUXDB_INIT_BUCKET=facility
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/ssafy_project_data/influxdb_data
      - influxdb_config:/ssafy_project_data/influxdb_config
    networks:
      - ssafy-network

  mongodb:
    image: mongo:7.0.9
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=[MongoDB Username]
      - MONGO_INITDB_ROOT_PASSWORD=[MongoDB Password]
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/ssafy_project_data/mongodb_data
      - mongodb_config:/ssafy_project_data/mongodb_config
    networks:
      - ssafy-network

  frontend:
    image: frontend-image:0.1
    restart: always
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
      - mongodb
    volumes:
      - frontend_data:/ssafy_project_data/frontend
    networks:
      - ssafy-network

  backend:
    image: backend-image:0.1
    restart: always
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - influxdb
      - mongodb
      - frontend
    volumes:
      - backend_data:/ssafy_project_data/backend
    networks:
      - ssafy-network

networks:
  ssafy-network:
    external: true

volumes:
  influxdb_data:
    driver: local
  influxdb_config:
    driver: local
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  frontend_data:
    driver: local
  backend_data:
    driver: local
